version: '3.9'

services:
  db:
    image: postgres:16
    container_name: profitly_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: profitly
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: profitly_web
    restart: always
    ports:
      - "5050:5000"
    depends_on:
      - db